#!/bin/bash
echo Hello, World

[D[A[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[B[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[B[B[A[A[C[C
ls
[A[C[A[C[C[C[C[B[D[D[D[D[D[B[A[A[A[B[B